name: CI
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install backend deps
        run: npm ci --prefix backend || npm install --prefix backend

      - name: Install frontend deps
        run: npm ci --prefix frontend || npm install --prefix frontend

      - name: Backend unit tests
        run: npm --prefix backend test --if-present

      - name: Frontend unit tests
        run: npm --prefix frontend test -- --watchAll=false