name: CI
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Workaround git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install backend deps
        working-directory: backend
        run: npm ci || npm install

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci || npm install

      - name: Backend unit tests
        working-directory: backend
        run: npm test --if-present

      - name: Frontend unit tests
        working-directory: frontend
        run: npm test --if-present -- --watchAll=false