name: CI
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Debug repo layout
        run: |
          pwd
          ls -la
          ls -la frontend || true
          ls -la backend || true

      - name: Install backend deps
        working-directory: backend
        run: npm install

      - name: Install frontend deps
        working-directory: frontend
        run: npm install

      - name: Backend unit tests
        working-directory: backend
        run: npm test --if-present

      - name: Frontend unit tests
        working-directory: frontend
        run: npm test -- --watchAll=false